# Generated by Django 4.2 on 2025-09-26 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodleContext',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contextlevel', models.IntegerField()),
            ],
            options={
                'db_table': 'mdl_context',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoodleRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shortname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mdl_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoodleRoleAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'mdl_role_assignments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoodleUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mdl_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('file_path', models.CharField(max_length=500)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
