# Generated by Django 4.2 on 2025-09-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eschool', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=50)),
                ('established_year', models.PositiveIntegerField()),
            ],
        ),
    ]
