
"""
Django settings for ignierp project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
#import environ


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
import os
from dotenv import load_dotenv
import os

load_dotenv()

MOODLE_BASE_URL = os.getenv("MOODLE_BASE_URL")
MOODLE_WS_TOKEN = os.getenv("MOODLE_WS_TOKEN")
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-417zqa0@u=x9tz1y_l^ioqvhve(i&a!_me@xjh#ga6oku_aw_u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['my.igniteict.com', 'www.my.igniteict.com','210.18.177.188','localhost','*']
CORS_ALLOW_ALL_ORIGINS = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

SESSION_ENGINE = "django.contrib.sessions.backends.db"  # default
SESSION_COOKIE_SECURE = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     "corsheaders",
#     "rest_framework",
#     'user_sessions',
#     'django_otp',
#     'django_otp.plugins.otp_static',
#     'django_otp.plugins.otp_totp',
#     'django_otp.plugins.otp_email',
#     'two_factor',
#     'two_factor.plugins.phonenumber',
#     'two_factor.plugins.email',
#     'debug_toolbar',
#     'bootstrapform',
#     "users",
#     "teachers",
#     'whitenoise.runserver_nostatic',
#      'eschool'

# ]


INSTALLED_APPS = [
    # Django core apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'corsheaders',
    'rest_framework',
    'user_sessions',
    'django_otp',
    'django_otp.plugins.otp_static',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_email',
    'two_factor',
    'two_factor.plugins.phonenumber',
    'two_factor.plugins.email',
    'debug_toolbar',
    'bootstrapform',
    'whitenoise.runserver_nostatic',

    # Local apps
    'eschool',
    'users',
    'teachers',
    'ckeditor',
    'ckeditor_uploader',
    'taggit',  # optional if you want image uploads
    'blog',
]


#MOODLE_BASE_URL = "https://staging.igniteict.com"
# MOODLE_BASE_URL = "http://210.18.177.188/igni"
# MOODLE_WS_TOKEN = "f7b2275d40d76bc3478eae17a791026f"   



CSRF_TRUSTED_ORIGINS = [
    "https://my.igniteict.com",
    "https://www.my.igniteict.com",
    "https://my.alpho.net",
    "https://www.my.alpho.net",
    "https://210.18.177.188",
    "http://210.18.177.188/igni",
]


#AUTH_USER_MODEL = 'eschool.CustomUser'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = '/login/'
#LOGIN_URL = 'two_factor:login'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',

    'django_otp.middleware.OTPMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'two_factor.middleware.threadlocals.ThreadLocals',

    
    "django.middleware.csrf.CsrfViewMiddleware",
    
    "django.contrib.messages.middleware.MessageMiddleware",
]


ROOT_URLCONF = 'ignierp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ignierp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': 'ignierp',
        'USER': 'myadmin',
        'PASSWORD': '453cur135',
        'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
        'PORT': '3306',
    },

    'moodle': {
            'ENGINE': 'django.db.backends.mysql',     # Moodle usually runs on MySQL/MariaDB
            'NAME': os.getenv('MOODLE_DB_NAME'),
            'USER': os.getenv('MOODLE_DB_USER'),
            'PASSWORD': os.getenv('MOODLE_DB_PASSWORD'),
            'HOST': os.getenv('MOODLE_DB_HOST', 'localhost'),
            'PORT': os.getenv('MOODLE_DB_PORT', '3306'),
        }
    }




# Internationalization

# Default language
LANGUAGE_CODE = 'en'

# Supported languages
LANGUAGES = [
    ('en','English'),
    ('ta', 'Tamil'),
]

# Paths to translation files
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

TIME_ZONE = 'UTC'

USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

FORCE_SCRIPT_NAME = '/erp'
USE_X_FORWARDED_HOST = True
STATIC_URL = '/erp/static/'


#STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Initialise django-environ
# env = environ.Env(
#     DEBUG=(bool, False)
# )
# environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
#MEDIA_URL = '/media/'
MEDIA_URL = '/erp/media/'
CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 400,
        'width': '100%',
    },
}


